spring:
  profiles:
    active: prod

server:
  error:
    include-stacktrace: on_param #always, never, on_param

api:
  security:
    token: ${JWT_SECRET:my-secret-key}

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: TRACE